const sequelize = require("../models/db");

async function seedPersonasPacientes() {
  const queryInterface = sequelize.getQueryInterface();

  // Insertar 15 personas
  await queryInterface.bulkInsert(
    "personas",
    [
      {
        dni: 27345123,
        nombre: "Juan",
        apellido: "Perez",
        f_nacimiento: "1985-04-12",
        genero: "Masculino",
        telefono: 2664123456,
        mail: "juan.perez@example.com",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        dni: 31234567,
        nombre: "Maria",
        apellido: "Gomez",
        f_nacimiento: "1990-09-30",
        genero: "Femenino",
        telefono: 2664987654,
        mail: "maria.gomez@example.com",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        dni: 25567890,
        nombre: "Carlos",
        apellido: "Diaz",
        f_nacimiento: "1978-02-20",
        genero: "Masculino",
        telefono: 2664123987,
        mail: "carlos.diaz@example.com",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        dni: 29876543,
        nombre: "Lucia",
        apellido: "Fernandez",
        f_nacimiento: "1995-07-15",
        genero: "Femenino",
        telefono: 2664123001,
        mail: "lucia.fernandez@example.com",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        dni: 32456789,
        nombre: "Mateo",
        apellido: "Sanchez",
        f_nacimiento: "1982-11-05",
        genero: "Masculino",
        telefono: 2664123777,
        mail: "mateo.sanchez@example.com",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        dni: 28765432,
        nombre: "Sofia",
        apellido: "Alvarez",
        f_nacimiento: "2000-01-22",
        genero: "Femenino",
        telefono: 2664123444,
        mail: "sofia.alvarez@example.com",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        dni: 30011223,
        nombre: "Diego",
        apellido: "Torres",
        f_nacimiento: "1975-05-18",
        genero: "Masculino",
        telefono: 2664132121,
        mail: "diego.torres@example.com",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        dni: 27654321,
        nombre: "Valentina",
        apellido: "Ruiz",
        f_nacimiento: "1998-12-02",
        genero: "Femenino",
        telefono: 2664123222,
        mail: "valentina.ruiz@example.com",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        dni: 29012345,
        nombre: "Andres",
        apellido: "Ramirez",
        f_nacimiento: "1987-03-08",
        genero: "Masculino",
        telefono: 2664123555,
        mail: "andres.ramirez@example.com",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        dni: 30543210,
        nombre: "Camila",
        apellido: "Suarez",
        f_nacimiento: "1993-06-25",
        genero: "Femenino",
        telefono: 2664123666,
        mail: "camila.suarez@example.com",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        dni: 26543211,
        nombre: "Martin",
        apellido: "Castro",
        f_nacimiento: "1979-10-11",
        genero: "Masculino",
        telefono: 2664123888,
        mail: "martin.castro@example.com",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        dni: 28345678,
        nombre: "Martina",
        apellido: "Morales",
        f_nacimiento: "1988-08-03",
        genero: "Femenino",
        telefono: 2664123999,
        mail: "martina.morales@example.com",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        dni: 29987654,
        nombre: "Lucas",
        apellido: "Herrera",
        f_nacimiento: "1992-04-17",
        genero: "Masculino",
        telefono: 2664123111,
        mail: "lucas.herrera@example.com",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        dni: 27890123,
        nombre: "Paula",
        apellido: "Navarro",
        f_nacimiento: "1984-09-09",
        genero: "Femenino",
        telefono: 2664123223,
        mail: "paula.navarro@example.com",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        dni: 31012345,
        nombre: "Nicolas",
        apellido: "Vidal",
        f_nacimiento: "1991-02-28",
        genero: "Masculino",
        telefono: 2664123333,
        mail: "nicolas.vidal@example.com",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    {}
  );

  // Insertar 15 pacientes asociados
  await queryInterface.bulkInsert(
    "pacientes",
    [
      {
        id_persona: 1,
        contacto: 27345123,
        direccion: "Calle Mitre 123",
        id_obra_social: 1,
        cod_os: 1001,
        detalle: null,
        estado: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_persona: 2,
        contacto: 31234567,
        direccion: "Av. San Martin 456",
        id_obra_social: 2,
        cod_os: 1002,
        detalle: "Alergia a penicilina",
        estado: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_persona: 3,
        contacto: 25567890,
        direccion: "Calle Rivadavia 789",
        id_obra_social: 3,
        cod_os: 1003,
        detalle: null,
        estado: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_persona: 4,
        contacto: 29876543,
        direccion: "Av. Belgrano 101",
        id_obra_social: 4,
        cod_os: 1004,
        detalle: "Hipertension",
        estado: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_persona: 5,
        contacto: 32456789,
        direccion: "Calle San Juan 202",
        id_obra_social: 5,
        cod_os: 1005,
        detalle: null,
        estado: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_persona: 6,
        contacto: 28765432,
        direccion: "Av. 9 de Julio 303",
        id_obra_social: 1,
        cod_os: 1006,
        detalle: "Diabetes tipo 2",
        estado: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_persona: 7,
        contacto: 30011223,
        direccion: "Calle Italia 404",
        id_obra_social: 2,
        cod_os: 1007,
        detalle: null,
        estado: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_persona: 8,
        contacto: 27654321,
        direccion: "Av. Pueyrredon 505",
        id_obra_social: 3,
        cod_os: 1008,
        detalle: null,
        estado: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_persona: 9,
        contacto: 29012345,
        direccion: "Calle Corrientes 606",
        id_obra_social: 4,
        cod_os: 1009,
        detalle: "Asma",
        estado: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_persona: 10,
        contacto: 30543210,
        direccion: "Av. Lavalle 707",
        id_obra_social: 5,
        cod_os: 1010,
        detalle: null,
        estado: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_persona: 11,
        contacto: 26543211,
        direccion: "Calle Sarmiento 808",
        id_obra_social: 1,
        cod_os: 1011,
        detalle: null,
        estado: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_persona: 12,
        contacto: 28345678,
        direccion: "Av. Colón 909",
        id_obra_social: 2,
        cod_os: 1012,
        detalle: "Embarazada",
        estado: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_persona: 13,
        contacto: 29987654,
        direccion: "Calle Rioja 112",
        id_obra_social: 3,
        cod_os: 1013,
        detalle: null,
        estado: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_persona: 14,
        contacto: 27890123,
        direccion: "Av. España 223",
        id_obra_social: 4,
        cod_os: 1014,
        detalle: null,
        estado: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_persona: 15,
        contacto: 31012345,
        direccion: "Calle Rioja 334",
        id_obra_social: 5,
        cod_os: 1015,
        detalle: "Problemas cardiacos",
        estado: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    {}
  );
}

module.exports = seedPersonasPacientes;
